export default {
  BUTTONS: 'BUTTONS',
  PROTETICA: 'PROTETICA',
  IMPLANTOLOGIE: 'IMPLANTOLOGIE',
  CHIRURGIE: 'CHIRURGIE',
  ODODONTIE: 'ODODONTIE',
  ENDODONTIE: 'ENDODONTIE',
  ORTODONTIE: 'ORTODONTIE',
};
